name: tarefas_novo
description: Projeto Flutter para o app NYX TASKS
publish_to: none

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  # Localização
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  table_calendar: ^3.0.9
  google_fonts: ^6.3.2
  url_launcher: ^6.3.2
  path: ^1.9.1
  stack_trace: ^1.12.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/plano_fundo4.png
